project_id = "npbhvkcitvowjbfrctfi"

[functions.send-contact-email]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-cod-order]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.fulfillment]
verify_jwt = false

[functions.geo-ip]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false
